"""Add stalker_hourly_presence table for device analytics

Revision ID: 1c2312b85e85
Revises: 636983efcbf3
Create Date: 2025-12-31 17:08:06.090931+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2312b85e85'
down_revision: Union[str, None] = '636983efcbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stalker_hourly_presence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('total_minutes_connected', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['stalker_tracked_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'day_of_week', 'hour_of_day', name='uix_device_hour_slot')
    )
    with op.batch_alter_table('stalker_hourly_presence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stalker_hourly_presence_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stalker_hourly_presence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stalker_hourly_presence_device_id'))

    op.drop_table('stalker_hourly_presence')
    # ### end Alembic commands ###
